### ISSUE TITLE
Toggle hotkey

### ISSUE THREAD

**Issue by j-peeters** [patrickchiang/obsidian-headings-in-explorer#3]
Hi, great idea to make headings visible in the file explorer, thanks. 
I wouldn't mind a toggle hotkey with which you can show or hide the headings. In my use case, I would probably only display them temporarily to quickly search for parts of a document and not have them visible all the time.

**Comment by patrickchiang** [comment]
Hey, I added an obsidian command to show/hide the headings to address #2 called "Toggle File Explorer Headings". You can set a hokey for that to turn on/off the feature quickly in your settings.

![342994856-bd21be77-120e-41b1-968c-2ede5ecebd9e](https://github.com/patrickchiang/obsidian-headings-in-explorer/assets/4903003/6f9106c9-add7-4556-943a-4969c9f45d97)

Does this resolve your issue, or is there something else we're looking for, like maybe a UI toggle?

**Comment by j-peeters** [comment]
That's already a great help, I was thinking though about a e.g. cmd-ctrl-h hotkey that I can press without having to run cmd-p and search for the toggle. Let me know what you think.

**Comment by patrickchiang** [comment]
> That's already a great help, I was thinking though about a e.g. cmd-ctrl-h hotkey that I can press without having to run cmd-p and search for the toggle. Let me know what you think.

Ah, I think that's already possible by going to hotkeys > search for the command > set the hotkey, like this:

![image](https://github.com/patrickchiang/obsidian-headings-in-explorer/assets/4903003/f7d63cd6-c96a-47c6-8fdb-fbb0ea26db9b)

The only reason I'm kind of resistant to adding a default hotkey for everyone is because the plugin guidelines strongly discourage default hotkeys due to possible conflicts.

**Comment by j-peeters** [comment]
Hi @patrickchiang how silly, I searched for heading and it didn't find anything. So I presumed the feature was not build in yet. Thanks for the pointer!
